server:
  port: 8080

spring:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create


  # JPA 설정


  #  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
#        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#        default_batch_fetch_size: ${chunkSize:100}
#        jdbc.batch_size: 20
#        order_inserts: true
#        order_updates: true
#        format_sql: true

  # Security OAuth
  security:
    oauth2.client:
      registration:
        google:
          clientId: '858872310817-cj48ltu8ldc2jhl9mm1b6f3lq2aju1mn.apps.googleusercontent.com'
          clientSecret: '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'
          scope:
            - email
            - profile
        #facebook:
          #clientId: '{페이스북 client-id}'
          #clientSecret: '{페이스북 client-secret}'
          #scope:
            #- email
            #- public_profile
        naver:
          clientId: 'l6bvyzn8BkUZEVMiBWoZ'
          clientSecret: 'nuydoLGmu3'
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "http://localhost:8080/login/oauth2/code/naver"
          scope:
            - nickname
            - email
            - profile_image
          clientName: Naver
        kakao:
          clientId: 'ea9c5ca0eadd181729719237dba8ec77'
          clientSecret: 'aFv4E0pqy4M9k1EbgQ4fYiyhHTLHPgpE'
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "http://localhost:8080/login/oauth2/code/kakao"
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider 설정
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id

# cors 설정
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds1'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect